name: network
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - boost=1.72.0
  - boost-cpp=1.72.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.24
  - cairo=1.16.0
  - certifi=2020.6.20
  - click=7.1.2
  - cycler=0.10.0
  - dbus=1.13.16
  - decorator=4.4.2
  - expat=2.2.9
  - flask=1.1.2
  - flask-cors=3.0.8
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.65.0
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - intel-openmp=2020.1
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - jpeg=9d
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - networkx=2.4
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.1.0
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.38.0
  - pycairo=1.19.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - qt=5.9.7
  - rdkit=2020.03.5
  - readline=8.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - tornado=6.0.4
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.11
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5


